{% set version = "1.16.0" %}

package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v{{ version }}.tar.gz
  sha256: bf1c1ce6583ea1ab805feceb000157dc1fb825a60ddac0fbd9a329a010f9ad72

build:
  skip: true  # [not linux or cuda_compiler_version in ("None", "11.2")]
  number: 0

outputs:
  - name: ucx
    version: {{ version }}
    build:
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
        - cuda-cudart-dev ={{ cuda_compiler_version }}     # [(cuda_compiler_version or "None").startswith("12")]
        - cuda-nvml-dev ={{ cuda_compiler_version }}       # [(cuda_compiler_version or "None").startswith("12")]
        - rdma-core
      run_constrained:
        - cuda-version >=11.2,<12  # [(cuda_compiler_version or "None").startswith("11")]
        - cuda-version >=12,<13    # [(cuda_compiler_version or "None").startswith("12")]

    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/lib/libucp${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucp.a"
        - test -f "${PREFIX}/lib/libucm${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucm.a"
        - test -f "${PREFIX}/lib/libucs${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucs.a"
        - test -f "${PREFIX}/lib/libuct${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libuct.a"
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        # Crashes qemu on ppc64le.
        - ${PREFIX}/bin/ucx_info -v         # [cuda_compiler_version == "None" and not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
    - xhochy
